name: Node.js CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          check-latest: true
      - name: Use npm 10.x
        run: npm i -g npm@^10
      - run: npm ci
      - run: npm test
